services:
  - type: web
    name: tanya-chatgpt-pro-malaysia
    env: node
    plan: free
    region: singapore
    rootDir: src
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
